version: "3"
services:
  node-app:
    build: . # must be here even though it's also in dev and prod files
    ports:
      - "3000:3000"
    env_file:
      - .env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sample_user
      - MONGO_INITDB_ROOT_PASSWORD=sample_pass
