version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sample_user
      - MONGO_INITDB_ROOT_PASSWORD=sample_pass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: # named volumes must also be declared
